openapi: 3.0.0
info:
  version: 1.0.0
  title: HOGE API
  description: HOGE API
servers:
  - url: 'https://api.dev.hoge.com'
    description: 開発環境
  - url: 'https://api.staging.hoge.com'
    description: 検証環境
  - url: 'https://api.hoge.com'
    description: 本番環境
security:
  - bearerAuth: []
tags:
  - name: /fuga
paths:
  $ref#books: "./common/paths/get/books.yaml"
components:
  schemas:
    $ref#error: "./components/error.yaml"
    $ref#book: "./components/book.yaml"
    
