openapi: 3.0.0
info:
  version: 1.0.0
  title: HOGE API
  description: HOGE API
servers:
  - url: 'https://api.dev.hoge.com'
    description: 開発環境
  - url: 'https://api.staging.hoge.com'
    description: 検証環境
  - url: 'https://api.hoge.com'
    description: 本番環境
security:
  - bearerAuth: []
tags:
  - name: /fuga
paths:
  /fuga/books/{id}:
    get:
      tags:
        - /fuga
      summary: 本情報取得
      description: |-
        ## API概要
        本情報を返却

        ---
        ## バリデーション
        - 参照権限がない場合は403
      responses:
        '200':
          description: 本情報を返却
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '403':
          description: エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      description: |-
        - エラー用のモデル
          - 項目に非依存なエラーはmessagesに格納
          - 項目ごとのエラーはdetailsに格納
      type: object
      properties:
        messages:
          type: array
          items:
            type: string
          example:
            - 権限が不足しています
        details:
          type: array
          items:
            $ref: '#/components/schemas/FieldError'
   Book:

