openapi: 3.0.0
info:
  version: 1.0.0
  title: GYRO BFF API
  description: |-
    GYROのBFF（Backends For Frontends）のAPI
servers:
  - url: https://api.development.bst-gyro.work
    description: 開発環境
  - url: https://api.staging.bst-gyro.work
    description: 検証環境
  - url: https://api.bst-gyro.work
    description: 本番環境
security:
  - bearerAuth: []
tags:
  - name: /common
  - name: /assessment
  - name: /reservation
paths:
  $ref#organizations: "./common/paths/get/organizations.yaml"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    $ref#error: "./components/error.yaml"
    $ref#field_error: "./components/field_error.yaml"
    $ref#organization: "./components/organization.yaml"
    $ref#organization_imitation: "./components/organization_imitation.yaml"